#cloud-config

users:
  - name: amani
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - "gh:Amani215"

package_update: true
package_upgrade: true
packages:
  - git
  - make

runcmd:
  - ["ufw", "allow", "80"]
  - ["ufw", "allow", "443"]
