{
 "title": "main dashboard",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Goalkeepers per Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  count(goalkeeper_id),\n  category_id\nFROM category_goalkeepers \nGROUP BY category_id\n",
     "rawQueryText": "SELECT\n  count(goalkeeper_id),\n  category_id\nFROM category_goalkeepers \nGROUP BY category_id\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Coaches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  count(id)\nFROM \"user\"\nwhere admin=0",
     "rawQueryText": "SELECT\n  count(id)\nFROM \"user\"\nwhere admin=0",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Admins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT count(id)\nFROM user\nWHERE admin=1",
     "rawQueryText": "SELECT count(id)\nFROM user\nWHERE admin=1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tallest Goalkeepers",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT  g.name as \"Goalkeeper\", MAX(gg.height) as \"Height\"\nFROM    goalkeeper g\nINNER JOIN(\n  SELECT  gm.goalkeeper_id, gm.height\n  FROM    growth_monitoring gm\n)gg ON gg.goalkeeper_id = g.id\ngroup by g.id\nORDER BY MAX(gg.height) DESC\nlimit 5",
     "rawQueryText": "SELECT  g.name as \"Goalkeeper\", MAX(gg.height) as \"Height\"\nFROM    goalkeeper g\nINNER JOIN(\n  SELECT  gm.goalkeeper_id, gm.height\n  FROM    growth_monitoring gm\n)gg ON gg.goalkeeper_id = g.id\ngroup by g.id\nORDER BY MAX(gg.height) DESC\nlimit 5",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Goalkeepers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  count(id)\nFROM goalkeeper",
     "rawQueryText": "SELECT\n  count(id)\nFROM goalkeeper",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Matches per Category",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  count(id),\n  category_id\t\nFROM\n  match\nGROUP BY\n  category_id",
     "rawQueryText": "SELECT\n  count(id),\n  category_id\t\nFROM\n  match\nGROUP BY\n  category_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Coaches per Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  count(user_id),\n  category_id\t\nFROM\n  category_trainers\nGROUP BY\n  category_id",
     "rawQueryText": "SELECT\n  count(user_id),\n  category_id\t\nFROM\n  category_trainers\nGROUP BY\n  category_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Absence",
   "type": "table",
   "description": "Top 5 absentees based on the last 3 months",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT  g.name as \"Goalkeeper\", COUNT(m.attendance) as \"Absences\"\nFROM    goalkeeper g\nINNER JOIN(\n  SELECT  tm.goalkeeper_id, tm.attendance\n  FROM    training_monitoring tm\n)m ON m.goalkeeper_id = g.id\ngroup by g.id\nORDER BY COUNT(m.attendance) DESC\nlimit 5",
     "rawQueryText": "SELECT  g.name as \"Goalkeeper\", COUNT(m.attendance) as \"Absences\"\nFROM    goalkeeper g\nINNER JOIN(\n  SELECT  tm.goalkeeper_id, tm.attendance\n  FROM    training_monitoring tm\n)m ON m.goalkeeper_id = g.id\ngroup by g.id\nORDER BY COUNT(m.attendance) DESC\nlimit 5",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}