---
version: '3'

services:
  web-ui:
    container_name: web-ui
    image: node:16.17.0-alpine3.15
    depends_on:
      - backend
    working_dir: /var/www/app
    volumes:
      - ./web-ui:/var/www/app
    command: sh -c ./run.sh
    restart: always
  backend:
    container_name: backend
    image: python:3.9-alpine3.15
    restart: always
    depends_on:
      - db
    working_dir: /var/www/app
    volumes:
      - ./api:/var/www/app
      - ./cache:/root/.m2
    environment:
      - FLASK_APP=__init__.py

    command: sh -c ./run.sh
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web-ui
      - backend
    restart: always

  adminer:
    image: michalhosna/adminer
    container_name: adminer
    restart: always
