---
version: '3'

volumes:
  pg-data: {}
  redis-data: {}
  minio: {}

services:
  web-ui:
    container_name: web-ui
    image: node:16.17.0-alpine3.15
    depends_on:
      - backend
    working_dir: /var/www/app
    volumes:
      - ./web-ui:/var/www/app
    command: sh -c ./run.sh
    restart: always

  backend:
    container_name: backend
    image: python:3.9-alpine3.15
    restart: always
    depends_on:
      - db
    working_dir: /var/www/app
    volumes:
      - ./api:/var/www/app
      - ./cache:/root/.m2
    env_file:
      - .env.dev
    command: sh -c ./run.sh

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web-ui
      - backend
    restart: always

  db:
    image: postgres:14-alpine3.16
    restart: always
    env_file:
      - .env.dev
    volumes:
      - pg-data:/var/lib/postgresql/data

  db-test:
    image: postgres:14-alpine3.16
    restart: always
    env_file:
      - .env.dev
    ports:
      - 5432:5432

  adminer:
    image: michalhosna/adminer
    container_name: adminer
    restart: always
    links:
      - db
    depends_on:
      - db

  redis:
    image: redis:7-alpine3.16
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/var/lib/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:6379
  
  minio:
    image: minio/minio:RELEASE.2022-09-25T15-44-53Z.fips
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
      - 9001
    volumes:
      - minio:/var/lib/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data