---
version: '3'

volumes:
  sqlite: {}
  redis-data: {}
  minio-data: {}

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - sqlite:/var/www/app/db:rw
    env_file:
      - .env
    environment:
      - SQLITE_HOST=//var/www/app/db/dev.db
    labels:
      - "traefik.http.routers.app.rule=Host(`docker.localhost`)"

  traefik:
    image: traefik:v2.11.0
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/configs/traefik:/etc/traefik:ro
    command:
      - --providers.docker=true
      - --api.insecure=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/test:/etc/nginx/conf.d
  #   depends_on:
  #     - app
  #   restart: always

  redis:
    image: redis:7-alpine3.16
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - redis-data:/var/lib/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:6379

  minio:
    image: minio/minio:RELEASE.2022-09-25T15-44-53Z.fips
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
      - 9001
    volumes:
      - minio-data:/var/lib/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  grafana:
    image: grafana/grafana:9.2.5-ubuntu
    container_name: grafana
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_INSTALL_PLUGINS=marcusolsson-calendar-panel,frser-sqlite-datasource
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./api/db:/api_db
