---
version: '3'

volumes:
  pg-data: {}
  redis-data: {}
  minio-data: {}

services:
  web-ui:
    container_name: web-ui
    image: node:21.6.2-alpine3.19
    depends_on:
      - backend
    working_dir: /var/www/app
    volumes:
      - ./web-ui:/var/www/app
    command: yarn start
    restart: always

  backend:
    container_name: backend
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    user: ${UID}:${GID}
    working_dir: /var/www/app
    volumes:
      - ./api:/var/www/app
    env_file:
      - .env
    command: python3 -m flask run --host=0.0.0.0

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
    depends_on:
      - web-ui
      - backend
    restart: always

  db:
    image: postgres:14-alpine3.16
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data

  db-test:
    image: postgres:14-alpine3.16
    container_name: db-test
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: michalhosna/adminer
    container_name: adminer
    restart: always
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./api/db:/api_db

  redis:
    image: redis:7-alpine3.16
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - redis-data:/var/lib/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:6379

  minio:
    image: minio/minio:RELEASE.2022-09-25T15-44-53Z.fips
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
      - 9001
    volumes:
      - minio-data:/var/lib/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  grafana:
    image: grafana/grafana:9.2.5-ubuntu
    container_name: grafana
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_INSTALL_PLUGINS=marcusolsson-calendar-panel,frser-sqlite-datasource
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./api/db:/api_db
