---
apiVersion: 1

deleteDatasources:
  - name: PostgreSQL
    orgId: 1

datasources:
  - name: SQLite
    access: proxy
    type: frser-sqlite-datasource
    url: ""
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials: false
    isDefault: true
    jsonData:
      path: /api_db/db.db
      pathPrefix: "file:"
    secureJsonData:
    version: 1
    editable: true
  - name: PostgreSQL
    access: proxy
    type: postgres
    url: db
    user: db
    database: db
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials: false
    isDefault: false
    jsonData:
      postgresVersion: 1400
      sslmode: disable
    secureJsonData:
      password: pass
    version: 1
    editable: true
