global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
    - targets: [minio:9000]

  - job_name: minio-job-node
    metrics_path: /minio/v2/metrics/node
    static_configs:
    - targets: [minio:9000]

  - job_name: minio-job-bucket
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
    - targets: [minio:9000]

  - job_name: minio-job-resource
    metrics_path: /minio/v2/metrics/resource
    static_configs:
    - targets: [minio:9000]

  - job_name: redis_exporter
    static_configs:
    - targets: ['redis-exporter:9121']
  