---
apiVersion: 1

deleteDatasources:
  - name: PostgreSQL
    orgId: 1

datasources:
  - name: SQLite
    access: proxy
    type: frser-sqlite-datasource
    url: ""
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials: false
    isDefault: true
    jsonData:
      path: /api_db/dev.db
      pathPrefix: "file:"
    secureJsonData:
    version: 1
    editable: true
  - name: prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials: false
    isDefault: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
    secureJsonData:
    version: 1
    editable: true
