{
 "title": "MinIO Replication Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Avg. Active Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_active_workers{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Avg. Link Latency (millis)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server, endpoint) (minio_cluster_replication_average_link_latency_ms{})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Avg. Queued Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_queued_bytes{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Avg. Queued Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_queued_count{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Avg. Transfer Rate (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_average_transfer_rate{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_current_active_workers{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Current Link Latency (millis)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_current_link_latency_ms{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Current Transfer Rate (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_current_transfer_rate{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Last Minute Queued",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_last_minute_queued_bytes{})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Last Minute Queued Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_replication_last_minute_queued_count{})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Link Downtime Duration (sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_link_downtime_duration_seconds{})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Link Offline Duration (sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_link_offline_duration_seconds{})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Max Active Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_active_workers{}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Link Latency (millis)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server, endpoint) (minio_cluster_replication_max_link_latency_ms{})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Max Queued Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_queued_bytes{}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Queued Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_queued_count{}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Transfer Rate (per sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_max_transfer_rate{}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Backlog (last 5 mins)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_recent_backlog_count{}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Link Online/Offline",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,endpoint) (minio_cluster_replication_link_online{})",
     "legendFormat": "{{server,endpoint}}"
    }
   ]
  },
  {
   "title": "Total Proxied Head Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_head_requests_total{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Head Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_head_requests_failures{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Put Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_put_tagging_requests_total{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Put Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_put_tagging_requests_failures{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_tagging_requests_total{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_tagging_requests_failures{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Delete Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_delete_tagging_requests_total{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Delete Tag Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_delete_tagging_requests_failures{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Proxied Get Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_requests_total{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Failed Proxied Get Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_cluster_replication_proxied_get_requests_failures{}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}