---
services:
  app:
    image: ghcr.io/amani215/goalkeeper-performance-tracker:master-alpine3.15
    container_name: app
    restart: always
    volumes:
      - app:/var/www/app/db"
    user: 100:100
    environment:
      - SQLITE_HOST=//var/www/app/db/dev.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CACHE_TTL=86400 # Cache expires after 1 day
      - SECRET_KEY=${SECRET_KEY}
      - WTF_CSRF_SECRET_KEY=${WTF_CSRF_SECRET_KEY}
      - SQLALCHEMY_TRACK_MODIFICATIONS=True
      - DEBUG=True
      - FLASK_APP=app.py
      - TOKEN_EXPIRY_IN_SEC=3600
      - PUBLIC_S3=https://minio.{{ docker_platform_domain }}
      - PRIVATE_S3=http//minio:9000
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_DOMAIN=http://minio:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - PROFILE_PICS_BUCKET=${PROFILE_PICS_BUCKET}
      - GOALKEEPER_PICS_BUCKET=${GOALKEEPER_PICS_BUCKET}
      - TRAINING_FORMS_BUCKET=${TRAINING_FORMS_BUCKET}
      - DOCUMENTS_BUCKET=${DOCUMENTS_BUCKET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`{{ docker_platform_domain }}`)"

  redis:
    image: redis/redis-stack:7.2.0-v10
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis.{{ docker_platform_domain }}`)"
      - "traefik.http.services.redis.loadbalancer.server.port=8001"
      - "traefik.http.routers.redis.middlewares=basicauth@docker"

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z.fips
    container_name: minio
    restart: always
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minioconsole.rule=Host(`minioconsole.{{ docker_platform_domain }}`)"
      - "traefik.http.routers.minioconsole.service=minioconsole@docker"
      - "traefik.http.services.minioconsole.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio.rule=Host(`minio.{{ docker_platform_domain }}`)"
      - "traefik.http.routers.minio.service=minio@docker"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

volumes:
  app: {}
  minio: {}
  redis: {}

networks:
  default:
    name: "{{ docker_platform_network }}"
    external: true
