{
 "title": "main dashboard",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Goalkeepers per Category",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(goalkeeper_id),\n  category_id\nFROM category_goalkeepers \nGROUP BY category_id\n"
    }
   ]
  },
  {
   "title": "Coaches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM \"user\"\nwhere admin=false"
    }
   ]
  },
  {
   "title": "Admins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM \"user\"\nwhere admin=true"
    }
   ]
  },
  {
   "title": "Leaderboard ",
   "type": "barchart",
   "description": "Based on the 3 latest matches",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT  g.name as \"Goalkeeper\", AVG(gp.grade) as \"Grade Average\"\nFROM    goalkeeper g\nINNER JOIN(\n  SELECT  mm.main_goalkeeper_id, mm.grade\n  FROM    match_monitoring mm\n          INNER JOIN\n          (\n              SELECT id\n              FROM match\n              where date <= date(now())\n              ORDER BY \"date\" DESC\n              limit 3\n          ) m ON  mm.match_id = m.id\n)gp ON gp.main_goalkeeper_id = g.id\ngroup by g.id\nORDER BY AVG(gp.grade) DESC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Goalkeepers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM goalkeeper"
    }
   ]
  },
  {
   "title": "Matches per Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id),\n  category_id\t\nFROM\n  match\nGROUP BY\n  category_id\n"
    }
   ]
  },
  {
   "title": "Absence",
   "type": "table",
   "description": "Top 5 absentees based on the last 3 months",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT  g.name as \"Goalkeeper\", COUNT(tp.absent) as \"Number of Absences\"\nFROM    goalkeeper g\nINNER JOIN(\n  SELECT  tm.goalkeeper_id, tm.absent\n  FROM    training_monitoring tm\n          INNER JOIN\n          (\n              SELECT id\n              FROM training_session\n              where date <= date(now()) and date>= date_trunc('day', NOW() - interval '3 month')\n              ORDER BY \"date\" DESC\n              limit 3\n          ) t ON  tm.session_id = t.id\n)tp ON tp.goalkeeper_id = g.id\nwhere tp.absent=true\ngroup by g.id\nORDER BY COUNT(tp.absent) DESC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Coaches per Category",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(user_id),\n  category_id\t\nFROM\n  category_trainers\nGROUP BY\n  category_id\n"
    }
   ]
  }
 ]
}