"""Added: first login attribute to user

Revision ID: 09e385878bb3
Revises: 57979ec520ff
Create Date: 2023-04-28 17:34:50.264397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e385878bb3'
down_revision = '57979ec520ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_login')
    # ### end Alembic commands ###
