"""Added: match monitoring relationships

Revision ID: 11a8a90e2bd9
Revises: c235f4eb4f84
Create Date: 2022-11-10 15:40:06.305261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a8a90e2bd9'
down_revision = 'c235f4eb4f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('result', sa.String(length=35), nullable=True))
    op.add_column('match', sa.Column('score', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'score')
    op.drop_column('match', 'result')
    # ### end Alembic commands ###
