"""Added: uniqueness constraint on training session

Revision ID: 213ed48dc942
Revises: 773c9d582f27
Create Date: 2022-11-10 22:31:07.752771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213ed48dc942'
down_revision = '773c9d582f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'training_session', ['date', 'training_session_category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_session', type_='unique')
    # ### end Alembic commands ###
