"""Changed: date to datetime in trainings

Revision ID: 33cea9fcb968
Revises: 69d4f95f547d
Create Date: 2022-11-20 22:48:08.897247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cea9fcb968'
down_revision = '69d4f95f547d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
