"""Added: age column to goalkeepers

Revision ID: 5d34c50a5171
Revises: 
Create Date: 2022-11-08 00:18:20.516156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d34c50a5171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.add_column('goalkeeper', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goalkeeper', 'age')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
