"""Updated: calendar

Revision ID: 65e6d87e68af
Revises: 09e385878bb3
Create Date: 2023-07-15 16:02:48.933912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e6d87e68af'
down_revision = '09e385878bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'local')
    op.drop_column('calendar', 'visitor')
    op.drop_column('calendar', 'journey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('journey', sa.INTEGER(), nullable=False))
    op.add_column('calendar', sa.Column('visitor', sa.VARCHAR(length=128), nullable=False))
    op.add_column('calendar', sa.Column('local', sa.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
