"""Attendance time

Revision ID: 68c066eddf13
Revises: f12c01cdb285
Create Date: 2023-04-11 15:06:56.998433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c066eddf13'
down_revision = 'f12c01cdb285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_sequence', type_='foreignkey')
    op.create_foreign_key(None, 'match_sequence', 'match_monitoring', ['match_performance_id'], ['id'])
    op.drop_column('match_sequence', 'mstch_performance_id')
    op.add_column('training_monitoring', sa.Column('attendance_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_monitoring', 'attendance_time')
    op.add_column('match_sequence', sa.Column('mstch_performance_id', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'match_sequence', type_='foreignkey')
    op.create_foreign_key(None, 'match_sequence', 'match_monitoring', ['mstch_performance_id'], ['id'])
    # ### end Alembic commands ###
