"""Update: score local and score visitor to match

Revision ID: 69d4f95f547d
Revises: 213ed48dc942
Create Date: 2022-11-13 23:51:19.931499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d4f95f547d'
down_revision = '213ed48dc942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.add_column('match', sa.Column('score_local', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('score_visitor', sa.Integer(), nullable=True))
    op.drop_column('match', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('score', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.drop_column('match', 'score_visitor')
    op.drop_column('match', 'score_local')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
