"""Added: training session

Revision ID: 773c9d582f27
Revises: edf507bcd521
Create Date: 2022-11-10 19:08:20.436596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773c9d582f27'
down_revision = 'edf507bcd521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'match_monitoring', ['match_id', 'main_goalkeeper_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_monitoring', type_='unique')
    # ### end Alembic commands ###
