"""Added pic column to user

Revision ID: 99d8988861a6
Revises: b2923f4b2ffa
Create Date: 2022-10-03 20:13:19.083699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d8988861a6'
down_revision = 'b2923f4b2ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.add_column('user', sa.Column('profile_pic', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
