"""Removed: age column from goalkeepers

Revision ID: 9eb1d1c1cbd4
Revises: 5d34c50a5171
Create Date: 2022-11-08 00:39:52.226770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb1d1c1cbd4'
down_revision = '5d34c50a5171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goalkeeper', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goalkeeper', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
