"""moved training form

Revision ID: badca9bb6e82
Revises: 33cea9fcb968
Create Date: 2023-03-21 18:28:51.135861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badca9bb6e82'
down_revision = '33cea9fcb968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_monitoring', 'assets')
    op.drop_column('match_monitoring', 'flaws')
    op.drop_column('training_monitoring', 'training_form')
    op.add_column('training_session', sa.Column('training_form', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session', 'training_form')
    op.add_column('training_monitoring', sa.Column('training_form', sa.VARCHAR(length=128), nullable=True))
    op.add_column('match_monitoring', sa.Column('flaws', sa.VARCHAR(length=128), nullable=True))
    op.add_column('match_monitoring', sa.Column('assets', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
