"""Added: category id to match model

Revision ID: c235f4eb4f84
Revises: f57b2fa75d5a
Create Date: 2022-11-10 13:58:03.786363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c235f4eb4f84'
down_revision = 'f57b2fa75d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('category_id', sa.String(length=35), nullable=True))
    op.create_foreign_key(None, 'match', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'category_id')
    # ### end Alembic commands ###
