"""Added: user archive

Revision ID: e9c492aa4a91
Revises: 65e6d87e68af
Create Date: 2023-07-21 13:15:31.597649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c492aa4a91'
down_revision = '65e6d87e68af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('archived', sa.BOOLEAN(), nullable=False))
    op.add_column('user', sa.Column('archive_reason', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'archive_reason')
    op.drop_column('user', 'archived')
    # ### end Alembic commands ###
