"""Added: training time

Revision ID: f12c01cdb285
Revises: b671d6ea17f9
Create Date: 2023-04-09 17:01:23.254502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12c01cdb285'
down_revision = 'b671d6ea17f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_sequence', sa.Column('match_performance_id', sa.String(), nullable=True))
    op.drop_constraint(None, 'match_sequence', type_='foreignkey')
    op.create_foreign_key(None, 'match_sequence', 'match_monitoring', ['match_performance_id'], ['id'])
    op.drop_column('match_sequence', 'mstch_performance_id')
    op.add_column('training_monitoring', sa.Column('attendance_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_monitoring', 'attendance_time')
    op.add_column('match_sequence', sa.Column('mstch_performance_id', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'match_sequence', type_='foreignkey')
    op.create_foreign_key(None, 'match_sequence', 'match_monitoring', ['mstch_performance_id'], ['id'])
    op.drop_column('match_sequence', 'match_performance_id')
    # ### end Alembic commands ###
