"""Added: trainers current category

Revision ID: f57b2fa75d5a
Revises: 9eb1d1c1cbd4
Create Date: 2022-11-08 18:33:37.863242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f57b2fa75d5a'
down_revision = '9eb1d1c1cbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_category_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'user', 'category', ['current_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'current_category_id')
    # ### end Alembic commands ###
