{
 "title": "Match performance",
 "time": { "from": "2023-02-28T04:43:39.899Z", "to": "2023-03-01T04:43:39.899Z" },
 "templating": {
  "list": [
   {
    "name": "mpid",
    "query": "2c3f9f5f8ee74bc1b053b27a39a66ae9"
   }
  ]
 },
 "panels": [
  {
   "title": "Grade",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT grade\nFROM match_monitoring\nWHERE id = \"${mpid}\"",
     "rawQueryText": "SELECT grade\nFROM match_monitoring\nWHERE id = \"${mpid}\""
    }
   ]
  },
  {
   "title": "Time Played",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT time_played\nFROM match_monitoring",
     "rawQueryText": "SELECT time_played\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Balls Touched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT balls_touched\nFROM match_monitoring",
     "rawQueryText": "SELECT balls_touched\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Penalties",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "queryText": "SELECT penalties_saved as 'Saved', penalties_non_saved as 'Not saved'\nFROM match_monitoring",
     "rawQueryText": "SELECT penalties_saved as 'Saved', penalties_non_saved as 'Not saved'\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cards",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "queryText": "SELECT yellow_cards as 'Yellow', red_cards as 'Red'\nFROM match_monitoring",
     "rawQueryText": "SELECT yellow_cards as 'Yellow', red_cards as 'Red'\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Deliveries",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT successful_deliveries as 'Successful', non_successful_deliveries as 'Unsuccessful'\nFROM match_monitoring",
     "rawQueryText": "SELECT successful_deliveries as 'Successful', non_successful_deliveries as 'Unsuccessful'\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Ballon en Profondeur",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT successful_ballon_profondeur as 'Successful', non_successful_ballon_profondeur as 'Unsuccessful'\nFROM match_monitoring",
     "rawQueryText": "SELECT successful_ballon_profondeur as 'Successful', non_successful_ballon_profondeur as 'Unsuccessful'\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Reactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Hand relaunch",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT successful_hand_relaunch as 'Successful', non_successful_hand_relaunch as 'Unsuccessful'\nFROM match_monitoring",
     "rawQueryText": "SELECT successful_hand_relaunch as 'Successful', non_successful_hand_relaunch as 'Unsuccessful'\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Foot relaunch",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT successful_foot_relaunch as 'Successful', non_successful_foot_relaunch as 'Unsuccessful'\nFROM match_monitoring",
     "rawQueryText": "SELECT successful_foot_relaunch as 'Successful', non_successful_foot_relaunch as 'Unsuccessful'\nFROM match_monitoring",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}