name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io # GitHub Container Registry

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: install apt packages (make, gcc, g++)
        run: sudo apt install -y build-essential
      - name: install pip dependencies
        working-directory: ./api
        run: pip install -r requirements.txt
      - name: tests
        run: echo tests go here
  build:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for API
        id: api-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-api
      
      - name: Build and push API image
        uses: docker/build-push-action@v3
        with:
          context: api
          push: true
          tags: ${{ steps.api-meta.outputs.tags }}-alpine, ${{ steps.api-meta.outputs.tags }}-alpine3.15
          labels: ${{ steps.api-meta.outputs.labels }}
          file: api/Dockerfile