---
name: destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Destroy environment (Staging/Prod)"
        required: true
        default: staging
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.8.4

      - name: terraform init
        run: terraform init --upgrade
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}

      - name: terraform destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform/environments/${{ github.event.inputs.environment }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
